# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-19 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20190204_2348'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cartitem',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='active',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='carttotal',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='carttotal',
            name='user_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='Cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.carttotal'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_model.register_model'),
        ),
    ]
