# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-19 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190214_2003'),
        ('cart', '0009_auto_20190219_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_price'),
        ),
    ]
