# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-19 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cartitem_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_price',
        ),
    ]
