# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-06 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190203_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_price',
            name='price',
            field=models.IntegerField(default=0.0),
        ),
    ]
