# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-14 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190207_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_price',
            name='price',
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
