# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-14 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20190214_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_price',
            name='mrp',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_price',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
